// 시연용 합성 데이터입니다. 실제 고객·의료 데이터가 아닙니다.
//
// 이메일은 전부 @demo.test, 전화는 02-000-xxxx 로 두어 실재하는 연락처가
// 섞이지 않게 합니다. 날짜는 오늘 기준 offset(일) 이라 시연이 낡지 않습니다.

import type { Customer, CustomerSeed, CustomerSource, CustomerStatus } from './types'

import { addDays, iso, parseISO, TODAY, TODAY_ISO } from '@/utils/date'

/** 필터 선택지. 데이터에서 뽑지 않고 여기 두는 값이라 순서가 항상 단계 순입니다. */
export const CUSTOMER_STATUSES: CustomerStatus[] = ['신규', '제안', '협의', '계약', '보류']

export const CUSTOMER_SOURCES: CustomerSource[] = [
  '소개',
  '박람회',
  '홈페이지',
  '콜드콜',
  '기존 거래',
]

const customerSeed: CustomerSeed[] = [
  {
    id: 'FM-CU-2026-0001',
    name: '박서준',
    org: '한빛대학교병원',
    dept: '순환기내과',
    title: '과장',
    email: 'seojun.park@demo.test',
    phone: '02-000-1840',
    owner: '김지훈',
    source: '소개',
    status: '협의',
    lastOff: -7,
    nextOff: 0,
    createdOff: -164,
    memo: 'CardioView X7 도입 예산 확인 필요',
  },
  {
    id: 'FM-CU-2026-0002',
    name: '윤가영',
    org: '서림메디컬센터',
    dept: '영상의학과',
    title: '팀장',
    email: 'gayoung.yoon@demo.test',
    phone: '02-000-2731',
    owner: '김지훈',
    source: '박람회',
    status: '계약',
    lastOff: -2,
    nextOff: 0,
    createdOff: -212,
    memo: '사용 교육 일정 협의 중',
  },
  {
    id: 'FM-CU-2026-0003',
    name: '오정민',
    org: '새봄정형외과',
    dept: '원무팀',
    title: '대표원장',
    email: 'jeongmin.oh@demo.test',
    phone: '02-000-3677',
    owner: '이수민',
    source: '홈페이지',
    status: '제안',
    lastOff: -14,
    nextOff: null,
    createdOff: -88,
    memo: '견적 전달 후 회신 없음',
  },
  {
    id: 'FM-CU-2026-0004',
    name: '이민호',
    org: '한빛대학교병원',
    dept: '구매팀',
    title: '과장',
    email: 'minho.lee@demo.test',
    phone: '02-000-1098',
    owner: '김지훈',
    source: '기존 거래',
    status: '협의',
    lastOff: -21,
    nextOff: -3,
    createdOff: -301,
    memo: '연간 소모품 단가 재협의',
  },
  {
    id: 'FM-CU-2026-0005',
    name: '최수아',
    org: '정우병원',
    dept: '정보전략팀',
    title: '책임',
    email: 'sua.choi@demo.test',
    phone: '02-000-4432',
    owner: '박도윤',
    source: '소개',
    status: '제안',
    lastOff: -5,
    nextOff: 10,
    createdOff: -57,
    memo: 'PACS 연동 범위 확인',
  },
  {
    id: 'FM-CU-2026-0006',
    name: '정하늘',
    org: '도담재활병원',
    dept: '재활의학과',
    title: '실장',
    email: 'haneul.jeong@demo.test',
    phone: '02-000-5120',
    owner: '최가은',
    source: '박람회',
    status: '신규',
    lastOff: -1,
    nextOff: 4,
    createdOff: -12,
    memo: '전시 부스에서 명함 교환',
  },
  {
    id: 'FM-CU-2026-0007',
    name: '강도현',
    org: '미래아동병원',
    dept: '소아청소년과',
    title: '진료부장',
    email: 'dohyun.kang@demo.test',
    phone: '02-000-6248',
    owner: '이수민',
    source: '소개',
    status: '협의',
    lastOff: -9,
    nextOff: 2,
    createdOff: -140,
    memo: 'SonoFlex Pro 데모 요청',
  },
  {
    id: 'FM-CU-2026-0008',
    name: '한지우',
    org: '서림메디컬센터',
    dept: '구매팀',
    title: '차장',
    email: 'jiwoo.han@demo.test',
    phone: '02-000-2865',
    owner: '김지훈',
    source: '기존 거래',
    status: '계약',
    lastOff: -3,
    nextOff: 14,
    createdOff: -395,
    memo: '3분기 발주 예정',
  },
  {
    id: 'FM-CU-2026-0009',
    name: '문채원',
    org: '정우병원',
    dept: '간호부',
    title: '수간호사',
    email: 'chaewon.moon@demo.test',
    phone: '02-000-4519',
    owner: '박도윤',
    source: '콜드콜',
    status: '신규',
    lastOff: -4,
    nextOff: null,
    createdOff: -20,
    memo: '전극 패드 샘플 발송 대기',
  },
  {
    id: 'FM-CU-2026-0010',
    name: '배준영',
    org: '한빛대학교병원',
    dept: '심장혈관센터',
    title: '교수',
    email: 'junyoung.bae@demo.test',
    phone: '02-000-1276',
    owner: '김지훈',
    source: '소개',
    status: '계약',
    lastOff: -6,
    nextOff: 7,
    createdOff: -430,
    memo: '학술 심포지엄 공동 진행 논의',
  },
  {
    id: 'FM-CU-2026-0011',
    name: '서은비',
    org: '새봄정형외과',
    dept: '진료협력팀',
    title: '주임',
    email: 'eunbi.seo@demo.test',
    phone: '02-000-3391',
    owner: '이수민',
    source: '홈페이지',
    status: '보류',
    lastOff: -33,
    nextOff: null,
    createdOff: -95,
    memo: '내년 예산 편성 후 재논의',
  },
  {
    id: 'FM-CU-2026-0012',
    name: '노시현',
    org: '도담재활병원',
    dept: '구매팀',
    title: '과장',
    email: 'sihyun.noh@demo.test',
    phone: '02-000-5074',
    owner: '최가은',
    source: '박람회',
    status: '제안',
    lastOff: -11,
    nextOff: 1,
    createdOff: -63,
    memo: 'OrthoScan Mini 견적 검토 중',
  },
  {
    id: 'FM-CU-2026-0013',
    name: '임세아',
    org: '미래아동병원',
    dept: '원무팀',
    title: '팀장',
    email: 'sea.lim@demo.test',
    phone: '02-000-6712',
    owner: '이수민',
    source: '기존 거래',
    status: '협의',
    lastOff: -8,
    nextOff: -1,
    createdOff: -251,
    memo: '유지보수 계약 갱신 일정 확정 필요',
  },
  {
    id: 'FM-CU-2026-0014',
    name: '조현우',
    org: '서림메디컬센터',
    dept: '영상의학과',
    title: '전문의',
    email: 'hyunwoo.jo@demo.test',
    phone: '02-000-2088',
    owner: '김지훈',
    source: '소개',
    status: '제안',
    lastOff: -16,
    nextOff: 5,
    createdOff: -74,
    memo: '비교 견적 요청받음',
  },
  {
    id: 'FM-CU-2026-0015',
    name: '황유진',
    org: '정우병원',
    dept: '구매팀',
    title: '대리',
    email: 'yujin.hwang@demo.test',
    phone: '02-000-4903',
    owner: '박도윤',
    source: '콜드콜',
    status: '신규',
    lastOff: -2,
    nextOff: 3,
    createdOff: -9,
    memo: '첫 통화 완료, 자료 발송',
  },
  {
    id: 'FM-CU-2026-0016',
    name: '신태호',
    org: '한빛대학교병원',
    dept: '의공학팀',
    title: '팀장',
    email: 'taeho.shin@demo.test',
    phone: '02-000-1533',
    owner: '김지훈',
    source: '기존 거래',
    status: '계약',
    lastOff: -1,
    nextOff: 21,
    createdOff: -520,
    memo: '설치 환경 사전 점검 완료',
  },
  {
    id: 'FM-CU-2026-0017',
    name: '권나연',
    org: '새봄정형외과',
    dept: '간호부',
    title: '수간호사',
    email: 'nayeon.kwon@demo.test',
    phone: '02-000-3204',
    owner: '이수민',
    source: '소개',
    status: '신규',
    lastOff: -13,
    nextOff: null,
    createdOff: -30,
    memo: '사용 교육 희망 인원 확인 필요',
  },
  {
    id: 'FM-CU-2026-0018',
    name: '류정원',
    org: '도담재활병원',
    dept: '재활의학과',
    title: '전문의',
    email: 'jeongwon.ryu@demo.test',
    phone: '02-000-5661',
    owner: '최가은',
    source: '홈페이지',
    status: '협의',
    lastOff: -5,
    nextOff: 6,
    createdOff: -102,
    memo: '데모 장비 2주 대여 요청',
  },
  {
    id: 'FM-CU-2026-0019',
    name: '고민석',
    org: '미래아동병원',
    dept: '의공학팀',
    title: '주임',
    email: 'minseok.ko@demo.test',
    phone: '02-000-6019',
    owner: '이수민',
    source: '박람회',
    status: '보류',
    lastOff: -41,
    nextOff: null,
    createdOff: -118,
    memo: '담당자 변경 예정, 후임 확인 필요',
  },
  {
    id: 'FM-CU-2026-0020',
    name: '심보라',
    org: '서림메디컬센터',
    dept: '원무팀',
    title: '과장',
    email: 'bora.shim@demo.test',
    phone: '02-000-2447',
    owner: '김지훈',
    source: '기존 거래',
    status: '협의',
    lastOff: -10,
    nextOff: 8,
    createdOff: -188,
    memo: '결제 조건 조정 요청',
  },
  {
    id: 'FM-CU-2026-0021',
    name: '양우진',
    org: '정우병원',
    dept: '심장혈관센터',
    title: '교수',
    email: 'woojin.yang@demo.test',
    phone: '02-000-4155',
    owner: '박도윤',
    source: '소개',
    status: '제안',
    lastOff: -18,
    nextOff: -5,
    createdOff: -77,
    memo: '임상 사례 자료 요청받음',
  },
  {
    id: 'FM-CU-2026-0022',
    name: '표지호',
    org: '한빛대학교병원',
    dept: '원무팀',
    title: '대리',
    email: 'jiho.pyo@demo.test',
    phone: '02-000-1719',
    owner: '김지훈',
    source: '콜드콜',
    status: '신규',
    lastOff: -3,
    nextOff: 2,
    createdOff: -15,
    memo: '구매 절차 안내 예정',
  },
  {
    id: 'FM-CU-2026-0023',
    name: '진소율',
    org: '새봄정형외과',
    dept: '구매팀',
    title: '팀장',
    email: 'soyul.jin@demo.test',
    phone: '02-000-3548',
    owner: '이수민',
    source: '박람회',
    status: '계약',
    lastOff: -4,
    nextOff: 12,
    createdOff: -276,
    memo: '납품 일정 확정',
  },
  {
    id: 'FM-CU-2026-0024',
    name: '설민아',
    org: '도담재활병원',
    dept: '원무팀',
    title: '주임',
    email: 'mina.seol@demo.test',
    phone: '02-000-5892',
    owner: '최가은',
    source: '홈페이지',
    status: '제안',
    lastOff: -12,
    nextOff: null,
    createdOff: -49,
    memo: '견적서 재발송 필요',
  },
  {
    id: 'FM-CU-2026-0025',
    name: '남기훈',
    org: '미래아동병원',
    dept: '소아청소년과',
    title: '전문의',
    email: 'gihoon.nam@demo.test',
    phone: '02-000-6503',
    owner: '이수민',
    source: '소개',
    status: '신규',
    lastOff: -6,
    nextOff: 9,
    createdOff: -25,
    memo: '초음파 장비 관심',
  },
  {
    id: 'FM-CU-2026-0026',
    name: '차예린',
    org: '서림메디컬센터',
    dept: '간호부',
    title: '수간호사',
    email: 'yerin.cha@demo.test',
    phone: '02-000-2610',
    owner: '김지훈',
    source: '기존 거래',
    status: '계약',
    lastOff: -7,
    nextOff: 16,
    createdOff: -342,
    memo: '소모품 정기 배송 전환 완료',
  },
  {
    id: 'FM-CU-2026-0027',
    name: '방시우',
    org: '정우병원',
    dept: '의공학팀',
    title: '차장',
    email: 'siwoo.bang@demo.test',
    phone: '02-000-4771',
    owner: '박도윤',
    source: '박람회',
    status: '협의',
    lastOff: -15,
    nextOff: -2,
    createdOff: -131,
    memo: '설치 공간 실측 일정 재조율',
  },
  {
    id: 'FM-CU-2026-0028',
    name: '엄지수',
    org: '한빛대학교병원',
    dept: '간호부',
    title: '주임',
    email: 'jisu.eom@demo.test',
    phone: '02-000-1385',
    owner: '김지훈',
    source: '콜드콜',
    status: '보류',
    lastOff: -28,
    nextOff: null,
    createdOff: -66,
    memo: '부서 통합 이슈로 검토 중단',
  },
  {
    id: 'FM-CU-2026-0029',
    name: '천유빈',
    org: '새봄정형외과',
    dept: '재활의학과',
    title: '실장',
    email: 'yubin.cheon@demo.test',
    phone: '02-000-3970',
    owner: '이수민',
    source: '홈페이지',
    status: '제안',
    lastOff: -9,
    nextOff: 4,
    createdOff: -41,
    memo: '월 렌탈 방식 문의',
  },
  {
    id: 'FM-CU-2026-0030',
    name: '구본희',
    org: '도담재활병원',
    dept: '의공학팀',
    title: '과장',
    email: 'bonhee.gu@demo.test',
    phone: '02-000-5316',
    owner: '최가은',
    source: '소개',
    status: '협의',
    lastOff: -2,
    nextOff: 1,
    createdOff: -83,
    memo: '유지보수 범위 문서 전달',
  },
  {
    id: 'FM-CU-2026-0031',
    name: '주하람',
    org: '미래아동병원',
    dept: '구매팀',
    title: '대리',
    email: 'haram.joo@demo.test',
    phone: '02-000-6884',
    owner: '이수민',
    source: '기존 거래',
    status: '신규',
    lastOff: -20,
    nextOff: null,
    createdOff: -35,
    memo: '전임자 인수인계 중',
  },
  {
    id: 'FM-CU-2026-0032',
    name: '위성찬',
    org: '정우병원',
    dept: '원무팀',
    title: '팀장',
    email: 'seongchan.wi@demo.test',
    phone: '02-000-4288',
    owner: '박도윤',
    source: '박람회',
    status: '계약',
    lastOff: -5,
    nextOff: 18,
    createdOff: -207,
    memo: '연간 계약 체결, 첫 납품 준비',
  },
]

/** 담당 영업 목록. 데이터에서 뽑아야 필터와 목록이 어긋나지 않습니다. */
export const CUSTOMER_OWNERS: string[] = [...new Set(customerSeed.map((c) => c.owner))].sort()

export function toCustomer(seed: CustomerSeed): Customer {
  const next = seed.nextOff === null ? null : iso(addDays(TODAY, seed.nextOff))
  return {
    ...seed,
    last: iso(addDays(TODAY, seed.lastOff)),
    next,
    created: iso(addDays(TODAY, seed.createdOff)),
    overdue: next === null || next < TODAY_ISO,
  }
}

export const customers: Customer[] = customerSeed.map(toCustomer)

/** "3일 전" / "오늘" / "2일 뒤" — 목록에서 날짜 옆에 붙는 보조 라벨입니다. */
export function relativeDayLabel(isoDate: string): string {
  const days = Math.round((parseISO(isoDate).getTime() - TODAY.getTime()) / 86_400_000)
  if (days === 0) return '오늘'
  if (days < 0) return `${-days}일 전`
  return `${days}일 뒤`
}
